version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start 
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
      image: caddy:2.7.5
      ports:
        - ${PORT_HTTP:-80}:80
        - ${PORT_HTTPS:-443}:443

      volumes:
        - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      depends_on:
        - app